### ISSUE TITLE
can't open bag

### ISSUE THREAD

**Issue by yclwll** [blooblahguy/bdUI#1]
i can't open my bags,no error,can you fix it,no other addons

**Comment by Akridian** [comment]
New year, new issue.

Error on load .
![Снимок экрана 2020-10-16 183946](https://user-images.githubusercontent.com/18231421/96272732-8d704180-0fdf-11eb-9232-eb9f0a4c8e36.png)

Can't open bags. Instead got {bag_size}.{bag_num} messages in chat.
![Снимок экрана 2020-10-16 184027](https://user-images.githubusercontent.com/18231421/96272816-ad076a00-0fdf-11eb-9288-fd5915191ed4.png)

But I don't use 90% of addon. Just want to use Nameplates (Thanks again for joining addons).
![Снимок экрана 2020-10-16 184135](https://user-images.githubusercontent.com/18231421/96272957-d4f6cd80-0fdf-11eb-81d6-4b10ad76417a.png)
![Снимок экрана 2020-10-16 184209](https://user-images.githubusercontent.com/18231421/96272966-d7f1be00-0fdf-11eb-95e5-24e31907ed57.png)
