### ISSUE TITLE
Temp Weapon Enchants do not show

### ISSUE THREAD

**Issue by jstanley23** [blooblahguy/bdUI#19]
Temp weapon enchants (Like shaman windfury/flametongue) do not show up in the bdBuffs and show the old buff icons instead
![2020-11-27_11-40-23](https://user-images.githubusercontent.com/7001549/100892539-6e8f1700-3488-11eb-84c4-8651d25d3331.png)

**Comment by kyogoi** [comment]
With the buffs_debuffs rewrite in d0ae620fc88f9ada9c88365cbe2270aa35da6df5 this issue SHOULD be fixed, issue should prob be closed.

**Comment by gladelynch** [comment]
Fixed, just cleaning up issues. Thanks for the report!
