### ISSUE TITLE
[Bug] [New Bags] Attempting to split items returns "Couldn't split those items".

### ISSUE THREAD

**Issue by kyogoi** [blooblahguy/bdUI#36]
![image](https://user-images.githubusercontent.com/29696963/103611793-9db20180-4ee8-11eb-96b5-fdd8901e8137.png)
![image](https://user-images.githubusercontent.com/29696963/103611798-a0acf200-4ee8-11eb-8a20-88205eb6bb84.png)

**Comment by gladelynch** [comment]
This one works on every test i've got. I couldn't trigger or affect that error at all really, something is up with blizzard there. Are your bags full or is that item weird?
