### ISSUE TITLE
Bag Error

### ISSUE THREAD

**Issue by gubbih** [blooblahguy/bdUI#43]
Gets a lua error when opening all bags

**Comment by gladelynch** [comment]
You'll need to post the lua error itself before I can know how to help you

**Comment by tjohns34** [comment]
Hello blooblahguy,

I am getting lua errors too when looting NPCs, chests, etc, This may be the same issue as gubbih is seeing. The parts of bdUI I am using are Buffs & Debuffs and Nameplates. In my troubleshooting, I found that if I turn off the bdUI Nameplates, I don't get any errors. Here are the lua errors I'm seeing:

1)
Message: ...terface\AddOns\Blizzard_TokenUI\Blizzard_TokenUI.lua:202: attempt to index local 'watchButton' (a nil value)
Time: Fri Nov  5 16:08:15 2021
Count: 2
Stack: ...terface\AddOns\Blizzard_TokenUI\Blizzard_TokenUI.lua:202: attempt to index local 'watchButton' (a nil value)
[string "@Interface\AddOns\Blizzard_TokenUI\Blizzard_TokenUI.lua"]:202: in function `BackpackTokenFrame_Update'
[string "@Interface\FrameXML\MainMenuBar.lua"]:86: in function <Interface\FrameXML\MainMenuBar.lua:65>

Locals: (for index) = 4
(for limit) = 10
(for step) = 1
i = 4
watchButton = nil
currencyInfo = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'watchButton' (a nil value)"

2)
Message: Error loading Interface\AddOns\ZygorGuidesViewer\Data-Retail\Gold\xx_global.lua
Time: Fri Nov  5 16:08:19 2021
Count: 6

3)
Message: ...terface\AddOns\Blizzard_TokenUI\Blizzard_TokenUI.lua:202: attempt to index local 'watchButton' (a nil value)
Time: Fri Nov  5 16:09:17 2021
Count: 1
Stack: ...terface\AddOns\Blizzard_TokenUI\Blizzard_TokenUI.lua:202: attempt to index local 'watchButton' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Blizzard_TokenUI\Blizzard_TokenUI.lua"]:202: in function `BackpackTokenFrame_Update'
[string "@Interface\FrameXML\MainMenuBar.lua"]:86: in function <Interface\FrameXML\MainMenuBar.lua:65>

Locals: 

If there is any other info I can provide, I would be happy to do so. Please just let me know.

Thanks!

Tim

**Comment by Akridian** [comment]
I faced same issue as @tjohns34. Can't tell if it is related to 9.1.5 because wasn't playing for a while.

I use only Nameplates.
