### ISSUE TITLE
Weird item found - Mythic Keystone - Tazavesh, Streets

### ISSUE THREAD

**Issue by Baine** [blooblahguy/bdUI#52]
Getting this on retail:
![grafik](https://user-images.githubusercontent.com/6566469/192095038-3f7d6240-97bf-4d7d-9a1d-faf0093b56c7.png)

and bags don't load properly:
![grafik](https://user-images.githubusercontent.com/6566469/192095189-31ec9220-667d-490f-b008-6ae09d7ccd68.png)

**Comment by gladelynch** [comment]
Thanks for submitting this! I just pushed an update that should print more information for me to debug this. Will you update and screenshot the new error? It should look like the above but will print a full itemstring in chat as well.

**Comment by Baine** [comment]
for what it's worth, bags worked fine before receiving the mythic key stone
afterwards, it stopped, so I think it's related to how you handle them as items
![grafik](https://user-images.githubusercontent.com/6566469/194235314-5b92c7d1-f5dc-4089-bf94-2d6f41a83a91.png)
modules\bags\functions.lua#35 and modules\bags\functions.lua#58 respectively
split by colon, and the keystones I've encountered that with have two in their names alone

here's what the itemlink looks like as text (you'd have to escape the pipes by replacing each occurence with 2 pipes, see "Printing Links for Debug" at https://wowwiki-archive.fandom.com/wiki/ItemLink)
![grafik](https://user-images.githubusercontent.com/6566469/194238012-a56f6c3d-defe-4b5f-8b7c-1cae136ef7b4.png)

hope this helps and does not come off as condescending, as that's in no way meant that way :)
