### ISSUE TITLE
Dragonflight DebuffFrame

### ISSUE THREAD

**Issue by ddez180001** [blooblahguy/bdUI#54]
When enable the buffs_debuffs module, the blz default debuff frame is still visible.

Maybe we should also call `DebuffFrame:Hide()` when init the buffs_debuffs module? Seems blz add a **DebuffFrame** in Dragonflight.

![image](https://user-images.githubusercontent.com/11608915/210646831-b292c853-f222-444c-b054-4890c044adba.png)

**Comment by gladelynch** [comment]
I didn't see this earlier, but thanks for pointing it out! It's fixed in latest update
